/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 2 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 3 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 4 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 5 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 6 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 7 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 8 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 9 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 10 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 11 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 12 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 13 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 14 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 15 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 16 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 17 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 18 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 19 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 20 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 21 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 22 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 23 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 24 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 25 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 26 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 27 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 28 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 29 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 30 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 31 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 32 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 33 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 34 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 35 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 36 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 37 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 38 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 39 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 40 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 41 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 42 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 43 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 44 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 45 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 46 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 47 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 48 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hut -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hut -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hut &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d ST_TH_1L3B_Hct -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d ST_TH_1L3B_Hct -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d ST_TH_1L3B -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d ST_TH_1L3B -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d SingleElectronB &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d SingleElectronC &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d SingleElectronD &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d SingleMuonB &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d SingleMuonC &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b2j4.py -N 50000 -T 'sf' -t tr_all_b2j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b2j4 --vector  -d SingleMuonD &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 2 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hut &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hut &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d ST_TH_1L3B_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d ST_TH_1L3B &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d SingleElectronB &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d SingleElectronC &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d SingleElectronD &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d SingleMuonB &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d SingleMuonC &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j3.py -N 50000 -T 'sf' -t tr_all_b3j3 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j3 --vector  -d SingleMuonD &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 2 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 3 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 4 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 5 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 6 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 7 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 8 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 9 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 10 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 -c 11 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hut -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hut -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hut &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d ST_TH_1L3B_Hct -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d ST_TH_1L3B_Hct -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d ST_TH_1L3B -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d ST_TH_1L3B -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d SingleElectronB &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d SingleElectronC &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d SingleElectronD &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d SingleMuonB &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d SingleMuonC &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_MVAVars_b3j4.py -N 50000 -T 'sf' -t tr_all_b3j4 /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/MVAVars/b3j4 --vector  -d SingleMuonD &
PS="$PS $!"
