/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d ST_TH_1L3B &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d ST_TH_1L3B_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d TT_AntitopLeptonicDecay_TH_1L3B_Eta_Hut &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hct &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hut -c 0 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d TT_TopLeptonicDecay_TH_1L3B_Eta_Hut -c 1 &
PS="$PS $!"
/afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/lxbatch_runner.sh /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12 python prepareEventVariablesFriendTree_mvaVars.py -N 50000 -T 'sf' -t tr_m /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/INPUT /afs/cern.ch/work/c/cirkovic/FCNC/CMSSW_8_0_12/src/CMGTools/TTHAnalysis/macros/FTREES/mvaVars --vector  -d TT_TuneCUETP8M1_13TeV-powheg-pythia8 &
PS="$PS $!"
